default: pusher

engines:
 pusher:
  app_id: 7241
  key:    f36e789c57a0fc0ef70b
  secret: 1c66d57d4868ff817d5d
 keima:
  url: http://localhost:3001
  key: 4e7c45a1a2cb660517000001
 socky:
  http: http://localhost:3002/http
  web_socket: ws://localhost:3002/websocket
  app: as
  secret: my_secret
