development:
  url: <%= ENV['MONGOHQ_URL'] %>
test:
  url: <%= ENV['MONGOHQ_URL'] %>
# set these environment variables on your prod server
production:
  url: <%= ENV['MONGOHQ_URL'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

