development:
  host: <%= ENV['MONGODB_HOST'] %>
  database: <%= ENV['MONGODB_DATABASE'] %>
  username: <%= ENV['MONGODB_USERNAME'] %>
  password: <%= ENV['MONGODB_PASSWORD'] %>

test:
  host: localhost
  database: asakusa_satellite_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGODB_HOST'] %>
  database: <%= ENV['MONGODB_DATABASE'] %>
  username: <%= ENV['MONGODB_USERNAME'] %>
  password: <%= ENV['MONGODB_PASSWORD'] %>
  #uri: <%= ENV['MONGODB_URL'] %>
  #uri: <%= ENV['MONGOHQ_URL'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

