development:
  host: localhost
  database: asakusa_satellite_development

test:
  host: localhost
  database: asakusa_satellite_test

production:
  host: localhost
  port: 27017
  username: root
  password: pass
  database: asakusa_satellite
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
